import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const plantingGuides = [
  // Vegetables
  {
    name: 'Tomato',
    category: 'vegetable',
    scientificName: 'Solanum lycopersicum',
    description: 'One of the most popular garden vegetables, tomatoes come in thousands of varieties from tiny cherry tomatoes to massive beefsteaks.',
    generalInfo: 'Tomatoes are warm-season crops that originated in South America. They are technically fruits but are culinarily treated as vegetables. With proper care, a single tomato plant can produce 10-15 pounds of fruit per season.',
    funFacts: JSON.stringify([
      'Tomatoes were once considered poisonous in Europe because they are part of the nightshade family',
      'The largest tomato ever grown weighed over 10 pounds',
      'There are over 10,000 varieties of tomatoes worldwide',
      'Tomatoes are 95% water',
      'The first tomatoes in Europe were yellow, giving them the Italian name "pomodoro" (golden apple)'
    ]),
    variations: JSON.stringify([
      'Beefsteak - Large, meaty tomatoes perfect for slicing',
      'Cherry - Small, sweet tomatoes great for snacking and salads',
      'Roma/Plum - Oval-shaped with thick walls, ideal for sauces',
      'Heirloom - Open-pollinated varieties with unique colors and flavors',
      'Grape - Oblong cherry tomatoes that grow in clusters',
      'Green Zebra - Striped green variety with tangy flavor',
      'Brandywine - Classic heirloom known for exceptional flavor',
      'San Marzano - Italian paste tomato considered the best for sauce'
    ]),
    hardinessZones: JSON.stringify(['4a', '4b', '5a', '5b', '6a', '6b', '7a', '7b', '8a', '8b', '9a', '9b', '10a', '10b', '11a']),
    optimalZones: JSON.stringify(['5b', '6a', '6b', '7a', '7b', '8a', '8b']),
    zoneNotes: 'Tomatoes are frost-sensitive and require a long growing season. In colder zones, start indoors and use season extenders.',
    culinaryUses: 'Tomatoes are incredibly versatile - eat fresh in salads, sandwiches, and bruschetta; cook into sauces, soups, and stews; roast, grill, or sun-dry for concentrated flavor; can, pickle, or preserve for year-round enjoyment.',
    recipes: JSON.stringify([
      { name: 'Classic Marinara Sauce', description: 'Simple Italian tomato sauce with garlic, basil, and olive oil', prepTime: '30 minutes', ingredients: ['2 lbs fresh tomatoes', '4 cloves garlic', 'Fresh basil', 'Olive oil', 'Salt'] },
      { name: 'Caprese Salad', description: 'Fresh tomato slices layered with mozzarella and basil', prepTime: '10 minutes', ingredients: ['Ripe tomatoes', 'Fresh mozzarella', 'Fresh basil', 'Olive oil', 'Balsamic glaze'] },
      { name: 'Gazpacho', description: 'Refreshing cold Spanish tomato soup', prepTime: '20 minutes + chill time', ingredients: ['Tomatoes', 'Cucumber', 'Bell pepper', 'Garlic', 'Olive oil', 'Sherry vinegar'] },
      { name: 'Bruschetta', description: 'Toasted bread topped with fresh tomato mixture', prepTime: '15 minutes', ingredients: ['Diced tomatoes', 'Fresh basil', 'Garlic', 'Olive oil', 'Baguette'] }
    ]),
    flavorProfile: 'Ranges from sweet and fruity (cherry varieties) to rich and savory (beefsteaks). Heirlooms often have complex, wine-like notes. Acidity varies by variety and ripeness.',
    nutritionalInfo: 'Excellent source of vitamin C, potassium, folate, and vitamin K. Rich in lycopene, a powerful antioxidant that gives tomatoes their red color. Cooking actually increases lycopene availability.',
    medicinalUses: 'Lycopene in tomatoes has been studied for potential cardiovascular benefits and cancer prevention. Traditional medicine used tomato leaves (carefully - they contain toxins) as a poultice. Tomato juice has been used as a folk remedy for hangovers.',
    holisticUses: 'In companion planting, tomatoes help repel certain pests. Tomato leaf spray can deter aphids. The acidic juice can be used as a natural cleaning agent.',
    cautions: 'Tomato leaves and stems contain tomatine, which is toxic in large quantities. People with nightshade sensitivities may react to tomatoes. Green tomatoes contain solanine.',
    history: 'Tomatoes originated in western South America and were first domesticated in Mexico by the Aztecs. Spanish conquistadors brought them to Europe in the 16th century, where they were initially grown as ornamentals due to fears of toxicity.',
    culturalSignificance: 'The tomato is central to Italian, Spanish, and Mexican cuisines. La Tomatina festival in Spain involves massive tomato fights. In the US, the tomato is the official state vegetable of several states.',
    indoorStartWeeks: 6,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 12,
    daysToGerminate: 7,
    daysToMaturity: 70,
    minGerminationTemp: 60,
    optGerminationTemp: 75,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    soilPH: '6.0-6.8',
    spacing: '24-36 inches',
    plantingDepth: '1/4 inch',
    companionPlants: 'Basil, Carrots, Parsley, Marigolds, Asparagus, Celery',
    avoidPlants: 'Brassicas, Fennel, Corn, Potatoes, Walnuts',
    commonPests: 'Aphids, Hornworms, Whiteflies, Tomato Fruitworm',
    commonDiseases: 'Early Blight, Late Blight, Septoria Leaf Spot, Fusarium Wilt',
    organicPestControl: 'Hand-pick hornworms, use neem oil for aphids, introduce beneficial insects like ladybugs and parasitic wasps',
    harvestTips: 'Harvest when fruit is fully colored but still slightly firm. For best flavor, let ripen on the vine. Pick regularly to encourage more fruit production.',
    storageTips: 'Store at room temperature, never refrigerate as it destroys flavor and texture. Use within a week of ripening.',
    preservationMethods: 'Canning (whole, diced, or as sauce), freezing, drying, making paste or ketchup',
    notes: 'Stake or cage for support. Remove suckers for larger fruit. Consistent watering prevents blossom end rot.',
  },
  {
    name: 'Basil',
    category: 'herb',
    scientificName: 'Ocimum basilicum',
    description: 'A fragrant culinary herb essential to Mediterranean and Asian cuisines, known for its sweet, slightly peppery flavor.',
    generalInfo: 'Basil is one of the most beloved culinary herbs worldwide. It is a tender annual that thrives in warm weather and is a perfect companion plant for tomatoes both in the garden and kitchen.',
    funFacts: JSON.stringify([
      'The name basil comes from the Greek "basileus" meaning king',
      'In India, basil (tulsi) is considered sacred and is often planted around Hindu temples',
      'Ancient Egyptians used basil in the mummification process',
      'Basil can repel mosquitoes and flies',
      'There are over 60 varieties of basil with different flavors from cinnamon to lemon'
    ]),
    variations: JSON.stringify([
      'Sweet Basil - The classic variety for Italian cooking',
      'Genovese - Traditional pesto variety with large, tender leaves',
      'Thai Basil - Anise-flavored, essential for Southeast Asian cuisine',
      'Purple Basil - Beautiful ornamental with mild flavor',
      'Lemon Basil - Citrus notes, great for fish and desserts',
      'Holy Basil (Tulsi) - Sacred in Hinduism, medicinal properties',
      'Cinnamon Basil - Spicy-sweet flavor with cinnamon notes',
      'Greek Basil - Compact plant with small, intensely flavored leaves'
    ]),
    hardinessZones: JSON.stringify(['2a', '2b', '3a', '3b', '4a', '4b', '5a', '5b', '6a', '6b', '7a', '7b', '8a', '8b', '9a', '9b', '10a', '10b', '11a', '11b']),
    optimalZones: JSON.stringify(['7a', '7b', '8a', '8b', '9a', '9b', '10a']),
    zoneNotes: 'Basil is extremely frost-sensitive. In cooler zones, grow as an annual or bring indoors before first frost.',
    culinaryUses: 'Fresh basil is essential for pesto, Caprese salad, and Margherita pizza. Add to pasta sauces, soups, salads, and sandwiches. Thai basil is key to curries and stir-fries.',
    recipes: JSON.stringify([
      { name: 'Classic Pesto', description: 'Traditional Genovese basil sauce', prepTime: '15 minutes', ingredients: ['2 cups fresh basil', '1/3 cup pine nuts', '3 garlic cloves', '1/2 cup Parmesan', '1/2 cup olive oil'] },
      { name: 'Thai Basil Chicken', description: 'Spicy stir-fry with Thai basil', prepTime: '20 minutes', ingredients: ['Thai basil', 'Chicken', 'Garlic', 'Chili', 'Fish sauce', 'Oyster sauce'] },
      { name: 'Basil Lemonade', description: 'Refreshing summer drink', prepTime: '10 minutes', ingredients: ['Fresh basil', 'Lemons', 'Sugar', 'Water'] }
    ]),
    flavorProfile: 'Sweet, slightly peppery with hints of anise and clove. Flavor is most intense when fresh and diminishes with cooking.',
    nutritionalInfo: 'Good source of vitamin K, manganese, and antioxidants. Contains essential oils with anti-inflammatory properties.',
    medicinalUses: 'Traditionally used to aid digestion, reduce inflammation, and fight bacterial infections. Holy basil (tulsi) is used in Ayurvedic medicine for stress relief and immune support.',
    holisticUses: 'Used in aromatherapy for mental clarity and stress relief. A natural insect repellent. In garden companions, helps repel aphids and mosquitoes while attracting pollinators.',
    craftIdeas: JSON.stringify([
      { name: 'Basil-Infused Soap', description: 'Handmade soap bars with dried basil leaves and essential oil for a fresh, aromatic cleansing experience', materials: ['Melt-and-pour soap base', 'Dried basil leaves', 'Basil essential oil', 'Soap molds'], difficulty: 'Easy' },
      { name: 'Herb Wreath', description: 'A fragrant decorative wreath made with fresh basil and other herbs that dries beautifully', materials: ['Wire wreath form', 'Fresh basil bunches', 'Floral wire', 'Ribbon'], difficulty: 'Easy' },
      { name: 'Natural Room Spray', description: 'DIY air freshener with basil essential oil for a clean, uplifting scent', materials: ['Distilled water', 'Witch hazel', 'Basil essential oil', 'Spray bottle'], difficulty: 'Easy' },
      { name: 'Pressed Basil Art', description: 'Frame pressed basil leaves for botanical wall art', materials: ['Fresh basil leaves', 'Heavy books', 'Parchment paper', 'Picture frame'], difficulty: 'Easy' },
      { name: 'Herb-Infused Candles', description: 'Soy candles with dried basil for a subtle herbal fragrance', materials: ['Soy wax', 'Candle wicks', 'Dried basil', 'Essential oils', 'Jars'], difficulty: 'Medium' }
    ]),
    cautions: 'Generally safe, but holy basil may interact with blood-thinning medications. Pregnant women should consult a doctor before using basil supplements.',
    history: 'Basil originated in tropical regions from Africa to Southeast Asia. It has been cultivated for over 5,000 years and was brought to Europe by spice traders.',
    culturalSignificance: 'Sacred in Hinduism (tulsi), symbol of love in Italy, and used in Greek Orthodox church rituals. In some cultures, it was believed to bring good luck and ward off evil.',
    indoorStartWeeks: 6,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 6,
    daysToGerminate: 5,
    daysToMaturity: 30,
    minGerminationTemp: 70,
    optGerminationTemp: 75,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    soilPH: '6.0-7.0',
    spacing: '12-18 inches',
    plantingDepth: '1/4 inch',
    companionPlants: 'Tomatoes, Peppers, Oregano, Parsley',
    avoidPlants: 'Sage, Rue',
    commonPests: 'Aphids, Japanese Beetles, Slugs',
    commonDiseases: 'Fusarium Wilt, Downy Mildew',
    organicPestControl: 'Spray with neem oil, hand-pick beetles, use copper barriers for slugs',
    harvestTips: 'Pinch off flower buds to prolong leaf production. Harvest in the morning when oils are strongest. Take from the top to encourage bushier growth.',
    storageTips: 'Store fresh stems in water at room temperature. Do not refrigerate - leaves will turn black.',
    preservationMethods: 'Freeze in olive oil ice cubes, make pesto, dry (though flavor diminishes)',
    notes: 'Pinch growing tips regularly to promote bushiness. Successive plantings ensure continuous harvest.',
  },
  {
    name: 'Pepper',
    category: 'vegetable',
    scientificName: 'Capsicum annuum',
    description: 'Versatile vegetables ranging from sweet bell peppers to fiery hot varieties, adding color, flavor, and heat to cuisines worldwide.',
    generalInfo: 'Peppers are part of the nightshade family and are native to Central and South America. The heat in hot peppers comes from capsaicin, measured in Scoville Heat Units (SHU).',
    funFacts: JSON.stringify([
      'Bell peppers are actually fruits, not vegetables',
      'Red, yellow, and orange bell peppers are just ripe versions of green peppers',
      'The Carolina Reaper held the Guinness World Record for hottest pepper at over 2 million SHU',
      'Capsaicin (the heat compound) is used in pain relief creams',
      'Birds cannot taste capsaicin, which helps peppers spread their seeds',
      'Drinking milk helps with pepper heat better than water because capsaicin is fat-soluble'
    ]),
    variations: JSON.stringify([
      'Bell Pepper - Sweet, no heat, available in many colors',
      'Jalapeño - Mild to moderate heat (2,500-8,000 SHU)',
      'Serrano - Medium heat (10,000-25,000 SHU)',
      'Habanero - Very hot (100,000-350,000 SHU)',
      'Cayenne - Hot, used fresh or dried (30,000-50,000 SHU)',
      'Poblano - Mild when fresh, Ancho when dried',
      'Shishito - Mostly mild Japanese variety, occasional hot one',
      'Ghost Pepper (Bhut Jolokia) - Extremely hot (over 1 million SHU)'
    ]),
    hardinessZones: JSON.stringify(['4a', '4b', '5a', '5b', '6a', '6b', '7a', '7b', '8a', '8b', '9a', '9b', '10a', '10b', '11a']),
    optimalZones: JSON.stringify(['6a', '6b', '7a', '7b', '8a', '8b', '9a']),
    culinaryUses: 'Sweet peppers are delicious raw, roasted, stuffed, or in stir-fries. Hot peppers add heat to salsas, hot sauces, curries, and countless dishes. Dried peppers make chile powder and flakes.',
    recipes: JSON.stringify([
      { name: 'Stuffed Bell Peppers', description: 'Peppers filled with rice, meat, and cheese', prepTime: '45 minutes', ingredients: ['Bell peppers', 'Ground beef', 'Rice', 'Tomato sauce', 'Cheese'] },
      { name: 'Homemade Hot Sauce', description: 'Fermented hot pepper sauce', prepTime: '2 weeks (fermentation)', ingredients: ['Hot peppers', 'Garlic', 'Salt', 'Vinegar'] },
      { name: 'Roasted Red Pepper Hummus', description: 'Classic hummus with smoky roasted peppers', prepTime: '15 minutes', ingredients: ['Chickpeas', 'Roasted red peppers', 'Tahini', 'Garlic', 'Lemon'] }
    ]),
    flavorProfile: 'Ranges from sweet and fruity (bells) to earthy and complex (poblano) to intensely hot (superhots). Heat level varies by variety and growing conditions.',
    nutritionalInfo: 'Extremely high in vitamin C - one bell pepper has more than an orange. Also rich in vitamin A, B6, and antioxidants. Hot peppers boost metabolism.',
    medicinalUses: 'Capsaicin is used topically for pain relief and studied for cardiovascular benefits. Hot peppers may boost metabolism and have anti-inflammatory properties. Traditional medicine uses them for digestion and circulation.',
    holisticUses: 'Cayenne pepper is used in natural pest deterrents. Hot pepper sprays can deter garden pests. In some traditions, peppers are hung to ward off evil spirits.',
    cautions: 'Handle hot peppers with gloves - capsaicin can burn skin and eyes. Too much hot pepper can cause digestive distress. Those with GERD should limit consumption.',
    history: 'Peppers were domesticated in Mexico over 6,000 years ago. Columbus brought them to Europe, calling them "peppers" due to their spiciness. They spread rapidly to Asia and Africa.',
    culturalSignificance: 'Integral to Mexican, Thai, Indian, and Szechuan cuisines. Chili peppers feature in festivals worldwide. The pepper trade helped shape global commerce routes.',
    indoorStartWeeks: 8,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 10,
    daysToGerminate: 10,
    daysToMaturity: 60,
    minGerminationTemp: 65,
    optGerminationTemp: 80,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    soilPH: '6.0-6.8',
    spacing: '18-24 inches',
    plantingDepth: '1/4 inch',
    companionPlants: 'Tomatoes, Basil, Carrots, Onions, Spinach',
    avoidPlants: 'Fennel, Kohlrabi, Brassicas',
    commonPests: 'Aphids, Pepper Maggots, Hornworms',
    commonDiseases: 'Bacterial Spot, Anthracnose, Blossom End Rot',
    organicPestControl: 'Row covers, neem oil, hand-picking, companion planting with basil',
    harvestTips: 'Harvest peppers at any size. Let peppers ripen fully for sweeter flavor and more vitamins. Cut stems rather than pulling.',
    storageTips: 'Refrigerate for 1-2 weeks. Hot peppers can be stored longer.',
    preservationMethods: 'Freeze, dry, pickle, or make into sauce or powder',
    notes: 'Hot peppers need warm soil. Harvest regularly for continued production. Stress (less water) can increase heat.',
  },
  {
    name: 'Cucumber',
    category: 'vegetable',
    indoorStartWeeks: 3,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 8,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'high',
    companionPlants: 'Beans, Corn, Peas, Radishes, Sunflowers',
    avoidPlants: 'Potatoes, Aromatic Herbs',
    commonPests: 'Cucumber Beetles, Powdery Mildew',
    notes: 'Provide trellis for vining varieties. Keep well watered.',
  },
  {
    name: 'Lettuce',
    category: 'vegetable',
    indoorStartWeeks: 4,
    outdoorStartWeeks: -4,
    transplantWeeks: -2,
    harvestWeeks: 6,
    minGerminationTemp: 40,
    optGerminationTemp: 60,
    sunRequirement: 'partial shade',
    waterNeeds: 'moderate',
    companionPlants: 'Carrots, Radishes, Strawberries, Chives',
    avoidPlants: 'Celery',
    commonPests: 'Aphids, Slugs',
    notes: 'Succession plant every 2 weeks. Bolts in hot weather.',
  },
  {
    name: 'Carrot',
    category: 'vegetable',
    indoorStartWeeks: null,
    outdoorStartWeeks: -3,
    transplantWeeks: null,
    harvestWeeks: 10,
    minGerminationTemp: 45,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Lettuce, Onions, Tomatoes, Rosemary',
    avoidPlants: 'Dill',
    commonPests: 'Carrot Rust Fly, Aphids',
    notes: 'Direct sow only. Keep soil loose and well-drained.',
  },
  {
    name: 'Zucchini',
    category: 'vegetable',
    indoorStartWeeks: 3,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 7,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Corn, Beans, Nasturtiums',
    avoidPlants: 'Potatoes',
    commonPests: 'Squash Vine Borers, Powdery Mildew',
    notes: 'Harvest when small for best flavor. Very prolific.',
  },
  {
    name: 'Bean (Green)',
    category: 'vegetable',
    indoorStartWeeks: null,
    outdoorStartWeeks: 2,
    transplantWeeks: null,
    harvestWeeks: 8,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Corn, Squash, Carrots, Cucumber',
    avoidPlants: 'Onions, Garlic, Fennel',
    commonPests: 'Mexican Bean Beetles, Aphids',
    notes: 'Direct sow only. Pole beans need support.',
  },
  {
    name: 'Pea',
    category: 'vegetable',
    indoorStartWeeks: null,
    outdoorStartWeeks: -4,
    transplantWeeks: null,
    harvestWeeks: 10,
    minGerminationTemp: 40,
    optGerminationTemp: 55,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Carrots, Radishes, Turnips, Corn',
    avoidPlants: 'Onions, Garlic',
    commonPests: 'Pea Aphids, Powdery Mildew',
    notes: 'Plant early in spring. Provide support for climbing varieties.',
  },
  {
    name: 'Spinach',
    category: 'vegetable',
    indoorStartWeeks: 4,
    outdoorStartWeeks: -4,
    transplantWeeks: -2,
    harvestWeeks: 6,
    minGerminationTemp: 35,
    optGerminationTemp: 55,
    sunRequirement: 'partial shade',
    waterNeeds: 'moderate',
    companionPlants: 'Strawberries, Peas, Beans',
    avoidPlants: null,
    commonPests: 'Leaf Miners, Aphids',
    notes: 'Cool season crop. Bolts quickly in heat.',
  },
  {
    name: 'Broccoli',
    category: 'vegetable',
    indoorStartWeeks: 6,
    outdoorStartWeeks: -2,
    transplantWeeks: -2,
    harvestWeeks: 10,
    minGerminationTemp: 45,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Beets, Celery, Onions, Potatoes',
    avoidPlants: 'Tomatoes, Peppers, Strawberries',
    commonPests: 'Cabbage Worms, Aphids',
    notes: 'Harvest while heads are tight. Side shoots continue producing.',
  },
  {
    name: 'Kale',
    category: 'vegetable',
    indoorStartWeeks: 5,
    outdoorStartWeeks: -4,
    transplantWeeks: -2,
    harvestWeeks: 8,
    minGerminationTemp: 45,
    optGerminationTemp: 65,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Beets, Celery, Onions, Potatoes',
    avoidPlants: 'Tomatoes, Peppers, Strawberries',
    commonPests: 'Cabbage Worms, Aphids',
    notes: 'Frost improves flavor. Harvest outer leaves.',
  },
  {
    name: 'Onion',
    category: 'vegetable',
    indoorStartWeeks: 10,
    outdoorStartWeeks: -4,
    transplantWeeks: -2,
    harvestWeeks: 16,
    minGerminationTemp: 50,
    optGerminationTemp: 65,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Beets, Carrots, Lettuce, Tomatoes',
    avoidPlants: 'Beans, Peas',
    commonPests: 'Onion Maggots, Thrips',
    notes: 'Choose varieties suited to your latitude. Long-day vs short-day.',
  },
  {
    name: 'Garlic',
    category: 'vegetable',
    indoorStartWeeks: null,
    outdoorStartWeeks: -24,
    transplantWeeks: null,
    harvestWeeks: 36,
    minGerminationTemp: 32,
    optGerminationTemp: 50,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Tomatoes, Peppers, Brassicas, Fruit Trees',
    avoidPlants: 'Beans, Peas',
    commonPests: 'Few pest problems',
    notes: 'Plant in fall for summer harvest. Mulch well.',
  },
  {
    name: 'Radish',
    category: 'vegetable',
    indoorStartWeeks: null,
    outdoorStartWeeks: -4,
    transplantWeeks: null,
    harvestWeeks: 4,
    minGerminationTemp: 40,
    optGerminationTemp: 60,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Carrots, Lettuce, Peas, Cucumbers',
    avoidPlants: 'Hyssop',
    commonPests: 'Flea Beetles',
    notes: 'Fast growing. Great for succession planting.',
  },
  {
    name: 'Beet',
    category: 'vegetable',
    indoorStartWeeks: 4,
    outdoorStartWeeks: -2,
    transplantWeeks: 0,
    harvestWeeks: 8,
    minGerminationTemp: 50,
    optGerminationTemp: 65,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Broccoli, Bush Beans, Cabbage, Lettuce',
    avoidPlants: 'Pole Beans',
    commonPests: 'Leaf Miners',
    notes: 'Soak seeds before planting. Greens are edible too.',
  },
  // Herbs (Note: Basil is already defined above with full details)
  {
    name: 'Cilantro',
    category: 'herb',
    indoorStartWeeks: null,
    outdoorStartWeeks: -2,
    transplantWeeks: null,
    harvestWeeks: 4,
    minGerminationTemp: 50,
    optGerminationTemp: 65,
    sunRequirement: 'partial shade',
    waterNeeds: 'moderate',
    companionPlants: 'Most vegetables',
    avoidPlants: 'Fennel',
    commonPests: 'Few pest problems',
    notes: 'Bolts quickly in heat. Succession plant.',
  },
  {
    name: 'Parsley',
    category: 'herb',
    indoorStartWeeks: 8,
    outdoorStartWeeks: -2,
    transplantWeeks: 0,
    harvestWeeks: 8,
    minGerminationTemp: 50,
    optGerminationTemp: 65,
    sunRequirement: 'partial shade',
    waterNeeds: 'moderate',
    companionPlants: 'Tomatoes, Asparagus, Corn',
    avoidPlants: 'Lettuce, Mint',
    commonPests: 'Parsleyworm (Swallowtail caterpillar)',
    notes: 'Slow to germinate. Biennial plant.',
  },
  {
    name: 'Dill',
    category: 'herb',
    indoorStartWeeks: null,
    outdoorStartWeeks: 0,
    transplantWeeks: null,
    harvestWeeks: 8,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Cabbage, Cucumber, Lettuce, Onions',
    avoidPlants: 'Carrots',
    commonPests: 'Parsleyworm, Aphids',
    notes: 'Self-seeds readily. Attracts beneficial insects.',
  },
  {
    name: 'Mint',
    category: 'herb',
    indoorStartWeeks: 8,
    outdoorStartWeeks: 0,
    transplantWeeks: 0,
    harvestWeeks: 8,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'partial shade',
    waterNeeds: 'high',
    companionPlants: 'Cabbage, Tomatoes',
    avoidPlants: 'Parsley',
    commonPests: 'Spider Mites',
    notes: 'Very invasive! Grow in containers.',
  },
  {
    name: 'Rosemary',
    category: 'herb',
    indoorStartWeeks: 10,
    outdoorStartWeeks: 4,
    transplantWeeks: 4,
    harvestWeeks: 16,
    minGerminationTemp: 65,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Beans, Cabbage, Carrots',
    avoidPlants: null,
    commonPests: 'Few pest problems',
    notes: 'Slow to start from seed. Better from cuttings.',
  },
  {
    name: 'Thyme',
    category: 'herb',
    indoorStartWeeks: 8,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 12,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Most vegetables',
    avoidPlants: null,
    commonPests: 'Few pest problems',
    notes: 'Perennial in most zones. Well-draining soil.',
  },
  // Flowers
  {
    name: 'Marigold',
    category: 'flower',
    indoorStartWeeks: 6,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 8,
    minGerminationTemp: 65,
    optGerminationTemp: 75,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Tomatoes, Peppers, Most Vegetables',
    avoidPlants: 'Beans',
    commonPests: 'Spider Mites, Slugs',
    notes: 'Excellent pest deterrent. Deadhead for continuous blooms.',
  },
  {
    name: 'Sunflower',
    category: 'flower',
    indoorStartWeeks: null,
    outdoorStartWeeks: 2,
    transplantWeeks: null,
    harvestWeeks: 12,
    minGerminationTemp: 55,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Corn, Squash, Cucumbers',
    avoidPlants: 'Potatoes',
    commonPests: 'Birds, Squirrels',
    notes: 'Direct sow only. Provide support for tall varieties.',
  },
  {
    name: 'Zinnia',
    category: 'flower',
    indoorStartWeeks: 4,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 8,
    minGerminationTemp: 70,
    optGerminationTemp: 80,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Most vegetables',
    avoidPlants: null,
    commonPests: 'Powdery Mildew, Japanese Beetles',
    notes: 'Excellent cut flower. Attracts butterflies.',
  },
  {
    name: 'Nasturtium',
    category: 'flower',
    indoorStartWeeks: null,
    outdoorStartWeeks: 2,
    transplantWeeks: null,
    harvestWeeks: 8,
    minGerminationTemp: 55,
    optGerminationTemp: 65,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Squash, Cucumbers, Tomatoes',
    avoidPlants: null,
    commonPests: 'Aphids (trap crop)',
    notes: 'Edible flowers and leaves. Great trap crop for aphids.',
  },
  {
    name: 'Cosmos',
    category: 'flower',
    indoorStartWeeks: 4,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 10,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Most vegetables',
    avoidPlants: null,
    commonPests: 'Aphids, Thrips',
    notes: 'Self-seeds readily. Attracts beneficial insects.',
  },
  // Fruits
  {
    name: 'Strawberry',
    category: 'fruit',
    indoorStartWeeks: 10,
    outdoorStartWeeks: -2,
    transplantWeeks: -2,
    harvestWeeks: 52,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Beans, Lettuce, Onions, Spinach, Thyme',
    avoidPlants: 'Brassicas',
    commonPests: 'Birds, Slugs, Spider Mites',
    notes: 'Usually grown from transplants. Runners spread quickly.',
  },
  {
    name: 'Watermelon',
    category: 'fruit',
    indoorStartWeeks: 3,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 12,
    minGerminationTemp: 70,
    optGerminationTemp: 85,
    sunRequirement: 'full sun',
    waterNeeds: 'high',
    companionPlants: 'Corn, Sunflowers, Radishes',
    avoidPlants: 'Potatoes',
    commonPests: 'Cucumber Beetles, Aphids',
    notes: 'Needs warm soil and long season. Reduce water near harvest.',
  },
  {
    name: 'Cantaloupe',
    category: 'fruit',
    indoorStartWeeks: 3,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 11,
    minGerminationTemp: 70,
    optGerminationTemp: 85,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Corn, Sunflowers, Beans',
    avoidPlants: 'Potatoes',
    commonPests: 'Cucumber Beetles, Aphids',
    notes: 'Slip from vine when ripe. Sweet aroma indicates ripeness.',
  },
  {
    name: 'Pumpkin',
    category: 'fruit',
    indoorStartWeeks: 3,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 14,
    minGerminationTemp: 60,
    optGerminationTemp: 75,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Corn, Beans, Sunflowers',
    avoidPlants: 'Potatoes',
    commonPests: 'Squash Vine Borers, Powdery Mildew',
    notes: 'Needs lots of space. Harvest before hard frost.',
  },
]

async function main() {
  console.log('Start seeding...')
  
  // Clear existing data
  await prisma.plantingGuide.deleteMany()
  
  // Insert planting guides
  for (const guide of plantingGuides) {
    const result = await prisma.plantingGuide.create({
      data: guide,
    })
    console.log(`Created planting guide: ${result.name}`)
  }
  
  console.log('Seeding finished.')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
