import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const plantingGuides = [
  // Vegetables
  {
    name: 'Tomato',
    category: 'vegetable',
    indoorStartWeeks: 6,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 12,
    minGerminationTemp: 60,
    optGerminationTemp: 75,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Basil, Carrots, Parsley, Marigolds',
    avoidPlants: 'Brassicas, Fennel, Corn',
    commonPests: 'Aphids, Hornworms, Blight',
    notes: 'Stake or cage for support. Remove suckers for larger fruit.',
  },
  {
    name: 'Pepper',
    category: 'vegetable',
    indoorStartWeeks: 8,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 10,
    minGerminationTemp: 65,
    optGerminationTemp: 80,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Tomatoes, Basil, Carrots, Onions',
    avoidPlants: 'Fennel, Kohlrabi',
    commonPests: 'Aphids, Pepper Maggots',
    notes: 'Hot peppers need warm soil. Harvest regularly for continued production.',
  },
  {
    name: 'Cucumber',
    category: 'vegetable',
    indoorStartWeeks: 3,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 8,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'high',
    companionPlants: 'Beans, Corn, Peas, Radishes, Sunflowers',
    avoidPlants: 'Potatoes, Aromatic Herbs',
    commonPests: 'Cucumber Beetles, Powdery Mildew',
    notes: 'Provide trellis for vining varieties. Keep well watered.',
  },
  {
    name: 'Lettuce',
    category: 'vegetable',
    indoorStartWeeks: 4,
    outdoorStartWeeks: -4,
    transplantWeeks: -2,
    harvestWeeks: 6,
    minGerminationTemp: 40,
    optGerminationTemp: 60,
    sunRequirement: 'partial shade',
    waterNeeds: 'moderate',
    companionPlants: 'Carrots, Radishes, Strawberries, Chives',
    avoidPlants: 'Celery',
    commonPests: 'Aphids, Slugs',
    notes: 'Succession plant every 2 weeks. Bolts in hot weather.',
  },
  {
    name: 'Carrot',
    category: 'vegetable',
    indoorStartWeeks: null,
    outdoorStartWeeks: -3,
    transplantWeeks: null,
    harvestWeeks: 10,
    minGerminationTemp: 45,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Lettuce, Onions, Tomatoes, Rosemary',
    avoidPlants: 'Dill',
    commonPests: 'Carrot Rust Fly, Aphids',
    notes: 'Direct sow only. Keep soil loose and well-drained.',
  },
  {
    name: 'Zucchini',
    category: 'vegetable',
    indoorStartWeeks: 3,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 7,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Corn, Beans, Nasturtiums',
    avoidPlants: 'Potatoes',
    commonPests: 'Squash Vine Borers, Powdery Mildew',
    notes: 'Harvest when small for best flavor. Very prolific.',
  },
  {
    name: 'Bean (Green)',
    category: 'vegetable',
    indoorStartWeeks: null,
    outdoorStartWeeks: 2,
    transplantWeeks: null,
    harvestWeeks: 8,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Corn, Squash, Carrots, Cucumber',
    avoidPlants: 'Onions, Garlic, Fennel',
    commonPests: 'Mexican Bean Beetles, Aphids',
    notes: 'Direct sow only. Pole beans need support.',
  },
  {
    name: 'Pea',
    category: 'vegetable',
    indoorStartWeeks: null,
    outdoorStartWeeks: -4,
    transplantWeeks: null,
    harvestWeeks: 10,
    minGerminationTemp: 40,
    optGerminationTemp: 55,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Carrots, Radishes, Turnips, Corn',
    avoidPlants: 'Onions, Garlic',
    commonPests: 'Pea Aphids, Powdery Mildew',
    notes: 'Plant early in spring. Provide support for climbing varieties.',
  },
  {
    name: 'Spinach',
    category: 'vegetable',
    indoorStartWeeks: 4,
    outdoorStartWeeks: -4,
    transplantWeeks: -2,
    harvestWeeks: 6,
    minGerminationTemp: 35,
    optGerminationTemp: 55,
    sunRequirement: 'partial shade',
    waterNeeds: 'moderate',
    companionPlants: 'Strawberries, Peas, Beans',
    avoidPlants: null,
    commonPests: 'Leaf Miners, Aphids',
    notes: 'Cool season crop. Bolts quickly in heat.',
  },
  {
    name: 'Broccoli',
    category: 'vegetable',
    indoorStartWeeks: 6,
    outdoorStartWeeks: -2,
    transplantWeeks: -2,
    harvestWeeks: 10,
    minGerminationTemp: 45,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Beets, Celery, Onions, Potatoes',
    avoidPlants: 'Tomatoes, Peppers, Strawberries',
    commonPests: 'Cabbage Worms, Aphids',
    notes: 'Harvest while heads are tight. Side shoots continue producing.',
  },
  {
    name: 'Kale',
    category: 'vegetable',
    indoorStartWeeks: 5,
    outdoorStartWeeks: -4,
    transplantWeeks: -2,
    harvestWeeks: 8,
    minGerminationTemp: 45,
    optGerminationTemp: 65,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Beets, Celery, Onions, Potatoes',
    avoidPlants: 'Tomatoes, Peppers, Strawberries',
    commonPests: 'Cabbage Worms, Aphids',
    notes: 'Frost improves flavor. Harvest outer leaves.',
  },
  {
    name: 'Onion',
    category: 'vegetable',
    indoorStartWeeks: 10,
    outdoorStartWeeks: -4,
    transplantWeeks: -2,
    harvestWeeks: 16,
    minGerminationTemp: 50,
    optGerminationTemp: 65,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Beets, Carrots, Lettuce, Tomatoes',
    avoidPlants: 'Beans, Peas',
    commonPests: 'Onion Maggots, Thrips',
    notes: 'Choose varieties suited to your latitude. Long-day vs short-day.',
  },
  {
    name: 'Garlic',
    category: 'vegetable',
    indoorStartWeeks: null,
    outdoorStartWeeks: -24,
    transplantWeeks: null,
    harvestWeeks: 36,
    minGerminationTemp: 32,
    optGerminationTemp: 50,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Tomatoes, Peppers, Brassicas, Fruit Trees',
    avoidPlants: 'Beans, Peas',
    commonPests: 'Few pest problems',
    notes: 'Plant in fall for summer harvest. Mulch well.',
  },
  {
    name: 'Radish',
    category: 'vegetable',
    indoorStartWeeks: null,
    outdoorStartWeeks: -4,
    transplantWeeks: null,
    harvestWeeks: 4,
    minGerminationTemp: 40,
    optGerminationTemp: 60,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Carrots, Lettuce, Peas, Cucumbers',
    avoidPlants: 'Hyssop',
    commonPests: 'Flea Beetles',
    notes: 'Fast growing. Great for succession planting.',
  },
  {
    name: 'Beet',
    category: 'vegetable',
    indoorStartWeeks: 4,
    outdoorStartWeeks: -2,
    transplantWeeks: 0,
    harvestWeeks: 8,
    minGerminationTemp: 50,
    optGerminationTemp: 65,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Broccoli, Bush Beans, Cabbage, Lettuce',
    avoidPlants: 'Pole Beans',
    commonPests: 'Leaf Miners',
    notes: 'Soak seeds before planting. Greens are edible too.',
  },
  // Herbs
  {
    name: 'Basil',
    category: 'herb',
    indoorStartWeeks: 6,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 6,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Tomatoes, Peppers',
    avoidPlants: 'Sage, Rue',
    commonPests: 'Japanese Beetles, Aphids',
    notes: 'Pinch flowers to encourage leaf growth.',
  },
  {
    name: 'Cilantro',
    category: 'herb',
    indoorStartWeeks: null,
    outdoorStartWeeks: -2,
    transplantWeeks: null,
    harvestWeeks: 4,
    minGerminationTemp: 50,
    optGerminationTemp: 65,
    sunRequirement: 'partial shade',
    waterNeeds: 'moderate',
    companionPlants: 'Most vegetables',
    avoidPlants: 'Fennel',
    commonPests: 'Few pest problems',
    notes: 'Bolts quickly in heat. Succession plant.',
  },
  {
    name: 'Parsley',
    category: 'herb',
    indoorStartWeeks: 8,
    outdoorStartWeeks: -2,
    transplantWeeks: 0,
    harvestWeeks: 8,
    minGerminationTemp: 50,
    optGerminationTemp: 65,
    sunRequirement: 'partial shade',
    waterNeeds: 'moderate',
    companionPlants: 'Tomatoes, Asparagus, Corn',
    avoidPlants: 'Lettuce, Mint',
    commonPests: 'Parsleyworm (Swallowtail caterpillar)',
    notes: 'Slow to germinate. Biennial plant.',
  },
  {
    name: 'Dill',
    category: 'herb',
    indoorStartWeeks: null,
    outdoorStartWeeks: 0,
    transplantWeeks: null,
    harvestWeeks: 8,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Cabbage, Cucumber, Lettuce, Onions',
    avoidPlants: 'Carrots',
    commonPests: 'Parsleyworm, Aphids',
    notes: 'Self-seeds readily. Attracts beneficial insects.',
  },
  {
    name: 'Mint',
    category: 'herb',
    indoorStartWeeks: 8,
    outdoorStartWeeks: 0,
    transplantWeeks: 0,
    harvestWeeks: 8,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'partial shade',
    waterNeeds: 'high',
    companionPlants: 'Cabbage, Tomatoes',
    avoidPlants: 'Parsley',
    commonPests: 'Spider Mites',
    notes: 'Very invasive! Grow in containers.',
  },
  {
    name: 'Rosemary',
    category: 'herb',
    indoorStartWeeks: 10,
    outdoorStartWeeks: 4,
    transplantWeeks: 4,
    harvestWeeks: 16,
    minGerminationTemp: 65,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Beans, Cabbage, Carrots',
    avoidPlants: null,
    commonPests: 'Few pest problems',
    notes: 'Slow to start from seed. Better from cuttings.',
  },
  {
    name: 'Thyme',
    category: 'herb',
    indoorStartWeeks: 8,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 12,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Most vegetables',
    avoidPlants: null,
    commonPests: 'Few pest problems',
    notes: 'Perennial in most zones. Well-draining soil.',
  },
  // Flowers
  {
    name: 'Marigold',
    category: 'flower',
    indoorStartWeeks: 6,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 8,
    minGerminationTemp: 65,
    optGerminationTemp: 75,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Tomatoes, Peppers, Most Vegetables',
    avoidPlants: 'Beans',
    commonPests: 'Spider Mites, Slugs',
    notes: 'Excellent pest deterrent. Deadhead for continuous blooms.',
  },
  {
    name: 'Sunflower',
    category: 'flower',
    indoorStartWeeks: null,
    outdoorStartWeeks: 2,
    transplantWeeks: null,
    harvestWeeks: 12,
    minGerminationTemp: 55,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Corn, Squash, Cucumbers',
    avoidPlants: 'Potatoes',
    commonPests: 'Birds, Squirrels',
    notes: 'Direct sow only. Provide support for tall varieties.',
  },
  {
    name: 'Zinnia',
    category: 'flower',
    indoorStartWeeks: 4,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 8,
    minGerminationTemp: 70,
    optGerminationTemp: 80,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Most vegetables',
    avoidPlants: null,
    commonPests: 'Powdery Mildew, Japanese Beetles',
    notes: 'Excellent cut flower. Attracts butterflies.',
  },
  {
    name: 'Nasturtium',
    category: 'flower',
    indoorStartWeeks: null,
    outdoorStartWeeks: 2,
    transplantWeeks: null,
    harvestWeeks: 8,
    minGerminationTemp: 55,
    optGerminationTemp: 65,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Squash, Cucumbers, Tomatoes',
    avoidPlants: null,
    commonPests: 'Aphids (trap crop)',
    notes: 'Edible flowers and leaves. Great trap crop for aphids.',
  },
  {
    name: 'Cosmos',
    category: 'flower',
    indoorStartWeeks: 4,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 10,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'low',
    companionPlants: 'Most vegetables',
    avoidPlants: null,
    commonPests: 'Aphids, Thrips',
    notes: 'Self-seeds readily. Attracts beneficial insects.',
  },
  // Fruits
  {
    name: 'Strawberry',
    category: 'fruit',
    indoorStartWeeks: 10,
    outdoorStartWeeks: -2,
    transplantWeeks: -2,
    harvestWeeks: 52,
    minGerminationTemp: 60,
    optGerminationTemp: 70,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Beans, Lettuce, Onions, Spinach, Thyme',
    avoidPlants: 'Brassicas',
    commonPests: 'Birds, Slugs, Spider Mites',
    notes: 'Usually grown from transplants. Runners spread quickly.',
  },
  {
    name: 'Watermelon',
    category: 'fruit',
    indoorStartWeeks: 3,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 12,
    minGerminationTemp: 70,
    optGerminationTemp: 85,
    sunRequirement: 'full sun',
    waterNeeds: 'high',
    companionPlants: 'Corn, Sunflowers, Radishes',
    avoidPlants: 'Potatoes',
    commonPests: 'Cucumber Beetles, Aphids',
    notes: 'Needs warm soil and long season. Reduce water near harvest.',
  },
  {
    name: 'Cantaloupe',
    category: 'fruit',
    indoorStartWeeks: 3,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 11,
    minGerminationTemp: 70,
    optGerminationTemp: 85,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Corn, Sunflowers, Beans',
    avoidPlants: 'Potatoes',
    commonPests: 'Cucumber Beetles, Aphids',
    notes: 'Slip from vine when ripe. Sweet aroma indicates ripeness.',
  },
  {
    name: 'Pumpkin',
    category: 'fruit',
    indoorStartWeeks: 3,
    outdoorStartWeeks: 2,
    transplantWeeks: 2,
    harvestWeeks: 14,
    minGerminationTemp: 60,
    optGerminationTemp: 75,
    sunRequirement: 'full sun',
    waterNeeds: 'moderate',
    companionPlants: 'Corn, Beans, Sunflowers',
    avoidPlants: 'Potatoes',
    commonPests: 'Squash Vine Borers, Powdery Mildew',
    notes: 'Needs lots of space. Harvest before hard frost.',
  },
]

async function main() {
  console.log('Start seeding...')
  
  // Clear existing data
  await prisma.plantingGuide.deleteMany()
  
  // Insert planting guides
  for (const guide of plantingGuides) {
    const result = await prisma.plantingGuide.create({
      data: guide,
    })
    console.log(`Created planting guide: ${result.name}`)
  }
  
  // Create default user settings
  const existingSettings = await prisma.userSettings.findFirst()
  if (!existingSettings) {
    await prisma.userSettings.create({
      data: {
        hardinessZone: '7a',
        zipCode: '22201',
      },
    })
    console.log('Created default user settings')
  }
  
  console.log('Seeding finished.')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
